project_name: cfaccess-proxy

changelog:
  use: github
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999
  filters:
    exclude:
      - '^docs:'
      - typo
      - (?i)foo
      - 'ci'

before:
  hooks:
    - 'go mod download'
    - 'go mod tidy'

builds:
- env: [CGO_ENABLED=0]
  main: ./main.go
  goos:
    - linux
  goarch:
    - amd64
    - arm64
    - arm
  goarm:
    - 7
    - 6

dockers:
- image_templates:
  - "ghcr.io/j0sh3rs/{{.ProjectName}}:{{ .Version }}"
  - "ghcr.io/j0sh3rs/{{.ProjectName}}:latest"
  dockerfile: goreleaser.Dockerfile
  goos: linux
  goarch: amd64,arm,arm64
  goarm: 6,7
  use: buildx
  build_flag_templates:
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/j0sh3rs/cfaccess-proxy
  - --label=org.opencontainers.image.source=https://github.com/j0sh3rs/cfaccess-proxy
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=Apache-2.0
  - "--platform=linux/arm64/v8,linux/arm/v7,linux/amd64"
