project_name: cfaccess-proxy

before:
  hooks:
    - go mod download

builds:
- env:
    - CGO_ENABLED=0
  main: ./main.go
  goos:
    - linux
    - windows
    - darwin
  goarch:
    - amd64
    - arm64
  goarm:
    - 6
    - 7

dockers:
- image_templates: ["ghcr.io/j0sh3rs/cfaccess-proxy:{{ .Version }}"]
  dockerfile: Dockerfile
  build_flag_templates:
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/j0sh3rs/cfaccess-proxy
  - --label=org.opencontainers.image.source=https://github.com/j0sh3rs/cfaccess-proxy
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=Apache-2.0
