apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cfaccess-proxy
  name: cfaccess-proxy
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cfaccess-proxy
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cfaccess-proxy
    spec:
      containers:
        - image: ghcr.io/alexymantha/cfaccess-proxy
          name: cfaccess-proxy
          ports:
            - containerPort: 8080
          env:
            - name: AUTH_DOMAIN
              value: https://<your-own-domain>.cloudflareaccess.com
            - name: POLICY_AUD
              value: <YOUR_POLICY_AUD_TOKEN>
            - name: FORWARD_USER_HEADER
              value: X-Remote-User
            - name: FORWARD_EMAIL_HEADER
              value: X-Remote-Email
            - name: FORWARD_HOST
              value: <downstream-host>:<port>
            - name: LISTEN_ADDRESS
              value: :8080
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cfaccess-proxy
  name: cfaccess-proxy
  namespace: monitoring
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: cfaccess-proxy
