apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cfaccess-proxy
  name: cfaccess-proxy
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cfaccess-proxy
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cfaccess-proxy
    spec:
      containers:
        - image: ghcr.io/j0sh3rs/cfaccess-proxy
          name: cfaccess-proxy
          ports:
            - containerPort: 80
          env:
            - name: AUTHDOMAIN
              value: https://<your-own-domain>.cloudflareaccess.com
            - name: POLICYAUD
              value: <YOUR_POLICY_AUD_TOKEN>
            - name: FORWARDUSERHEADER
              value: X-WEBAUTH-USER
            - name: FORWARDEMAILHEADER
              value: X-WEBAUTH-EMAIL
            - name: FORWARDHOST
              value: <downstream-host>:<port>
            - name: ADDR
              value: :80
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cfaccess-proxy
  name: cfaccess-proxy
  namespace: monitoring
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: cfaccess-proxy
