name: Build-And-Publish

on:
  push:
    branches:
      - "main"

permissions:
  contents: write
  packages: write
  # issues: write

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out code
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.0
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
          default_bump: false
  build-and-release:
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out code
        with:
          fetch-depth: '0'
      - name: Fetch all tags
        run: git fetch --force --tags
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          args: release --rm-dist --debug
          distribution: goreleaser
          version: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
